# Generated by Django 4.2.4 on 2023-08-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_about_me_alter_profile_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='users/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('BOTH', 'Male and Female')], max_length=4, null=True),
        ),
    ]
