# Generated by Django 4.2.4 on 2023-12-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_groupofinterests_interest_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='relationship',
            field=models.CharField(choices=[('short', 'Short Relationship'), ('love', 'True Love'), ('friend', 'Friendship'), ('fun', 'Having Fun')], max_length=6, null=True),
        ),
    ]
