# Generated by Django 4.2.4 on 2023-12-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupofinterests',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=10),
        ),
    ]
