# Generated by Django 4.2.4 on 2023-12-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_userprofile_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('fake', 'Fake Profile'), ('harass', 'Harassment'), ('hate', 'Hate Speech'), ('scam', 'Scam'), ('picture', 'Inappropriate Picture'), ('underage', 'Underage User'), ('stalking', 'Stalking'), ('profile', 'Inappropriate Profile')], max_length=10, null=True),
        ),
    ]
