# Generated by Django 4.2.4 on 2023-12-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_report_report_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
