# Generated by Django 4.2.4 on 2024-05-17 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_likes_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_amount',
        ),
        migrations.AddField(
            model_name='comment',
            name='likes_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
